import type Mithril from 'mithril';
import Component, { ComponentAttrs } from 'flarum/common/Component';
import ItemList from 'flarum/common/utils/ItemList';
import Stream from 'flarum/common/utils/Stream';
import PollFormState from '../../states/PollFormState';
import PollModel from '../../models/Poll';
import PollOption from '../../models/PollOption';
export interface IPollFormAttrs extends ComponentAttrs {
    poll: PollModel;
    onsubmit: (data: object, state: PollFormState) => Promise<void>;
    allowDrafts?: boolean;
}
export default class PollForm extends Component<IPollFormAttrs, PollFormState> {
    protected options: PollOption[];
    protected optionAnswers: Stream<string>[];
    protected optionImageUrls: Stream<string>[];
    protected optionKeys: number[];
    protected nextOptionKey: number;
    protected question: Stream<string>;
    protected subtitle: Stream<string>;
    protected image: Stream<string | null>;
    protected imageAlt: Stream<string | null>;
    protected endDate: Stream<string | null>;
    protected publicPoll: Stream<boolean>;
    protected allowMultipleVotes: Stream<boolean>;
    protected hideVotes: Stream<boolean>;
    protected allowChangeVote: Stream<boolean>;
    protected maxVotes: Stream<number>;
    protected datepickerMinDate: string;
    protected pendingAction: 'draft' | 'publish' | null;
    protected snapshot: string;
    private beforeUnloadHandler;
    oninit(vnode: Mithril.Vnode<IPollFormAttrs, this>): void;
    oncreate(vnode: Mithril.VnodeDOM<IPollFormAttrs, this>): void;
    onremove(vnode: Mithril.VnodeDOM<IPollFormAttrs, this>): void;
    view(): Mithril.Children;
    fields(): ItemList<Mithril.Children>;
    imageField(): Mithril.Children;
    answersField(): Mithril.Children;
    answerItems(): ItemList<Mithril.Children>;
    endDateField(): Mithril.Children;
    endDateHelp(): Mithril.Children;
    settingsField(): Mithril.Children;
    settingItems(): ItemList<Mithril.Children>;
    submitItems(): ItemList<Mithril.Children>;
    publishSplitButton(): Mithril.Children;
    schedule(): void;
    deprecationNotice(hasImage: boolean, isUpload: boolean): Mithril.Children;
    addOption(): void;
    removeOption(i: number): void;
    data(): object;
    onsubmit(event: Event): Promise<void>;
    onSaveChanges(): Promise<void>;
    onSaveDraft(): Promise<void>;
    publish(): Promise<void>;
    submit(extra: object): Promise<boolean>;
    delete(): Promise<void>;
    protected handleError(error: unknown): void;
    protected successAlert(key: string): void;
    protected serializeFormState(): string;
    formatDate(date?: Date | string | false | undefined | null, def?: Date | false): string | false;
    dateToTimestamp(date: string | null): string | null;
    pollImageUploadSuccess(fileName: string | null | undefined): void;
    pollOptionImageUploadSuccess(index: number, fileName: string | null | undefined): void;
}
