import type Mithril from 'mithril';
import Component from 'flarum/common/Component';
import ItemList from 'flarum/common/utils/ItemList';
import Poll from '../models/Poll';
type Context = Component<any, any>;
declare const _default: {
    controls(poll: Poll, context: Context): ItemList<Mithril.Children>;
    pollControls(poll: Poll, context: Context): ItemList<Mithril.Children>;
    moderationControls(poll: Poll, context: Context): ItemList<Mithril.Children>;
    destructiveControls(poll: Poll, context: Context): ItemList<Mithril.Children>;
    editAction(poll: Poll): void;
    scheduleAction(poll: Poll): void;
    deleteAction(poll: Poll): Promise<void>;
    publishAction(poll: Poll): Promise<void>;
    cancelScheduleAction(poll: Poll): Promise<void>;
    unpublishAction(poll: Poll): Promise<void>;
    alert(type: 'success' | 'error', key: string): void;
    errorAlert(error: any): void;
};
export default _default;
